### ISSUE TITLE
Remember to use ===

### ISSUE THREAD

**Issue by jamiecoe** [aysam199/ToDo_project#18]
I see a few examples where you are using `==` to check equality (eg: [here](https://github.com/aysam199/ToDo_project/blob/30b2c1f952662598417a169cf5eca044323ef6d6/dom.js#L86))

Remember that it's safer to use `===` as this checks strict equality (including types). Eg:
```js
"1" == 1 // true
"1" === 1 // false
1 === 1 // true
```
It's better to be strict, as it avoids confusing bugs that are difficult to find.

**Comment by Fatmeeh** [comment]
Done
